/**
 * Buyer-Centric Cost & Margin Analyzer - Result Dashboard
 * 
 * One-screen dashboard with:
 * - Cost View
 * - Margin View
 * - Feasibility Score
 * 
 * Exportable summary (PDF/Excel)
 */

import { useState } from 'react';
import {
    Alert,
    Dimensions,
    ScrollView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import { buildMarginAnalysisData, generateExcelMarginAnalysis, generatePdfMarginAnalysis, shareFile } from '../utils/exporters';
import {
    CURRENCIES,
    getMarginStatusColor,
    getMarginStatusLabel
} from '../utils/marginAnalyzer';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const BuyerAnalyzerResultScreen = ({ route, navigation }) => {
    const { inputs, analysis } = route.params;
    const [activeView, setActiveView] = useState('margin'); // margin, cost

    const currencySymbol = CURRENCIES[inputs.currency]?.symbol || '$';

    // ========== SHARING FUNCTIONS ==========

    const handleShareText = async () => {
        const message = `📊 *MARGIN ANALYSIS REPORT*

*Style:* ${inputs.styleName || 'N/A'}
*Buyer:* ${inputs.buyerName || 'N/A'}

*PRICING:*
• Buyer Target: ${currencySymbol}${analysis.inputs.buyerTargetFob.toFixed(2)}
• Your Quote: ${currencySymbol}${analysis.inputs.quotedFob.toFixed(2)}
• Price Gap: ${currencySymbol}${analysis.priceGap.toFixed(2)} (${analysis.priceGapPercent.toFixed(1)}%)

*COST BREAKDOWN:*
• Total Cost: ${currencySymbol}${analysis.totalCost.toFixed(2)}/pc
• Break-even FOB: ${currencySymbol}${analysis.breakEvenFob.toFixed(2)}

*MARGIN ANALYSIS:*
• Gross Margin: ${currencySymbol}${analysis.grossMargin.toFixed(2)}/pc
• Margin %: ${analysis.marginPercent.toFixed(1)}%
• Status: ${getMarginStatusLabel(analysis.marginPercent)}

*FEASIBILITY:*
• Score: ${analysis.feasibilityScore.score}/100
• Status: ${analysis.feasibilityScore.status}
• Recommendation: ${analysis.feasibilityScore.recommendation}

*ORDER VALUE:*
• Quantity: ${analysis.inputs.orderQuantity.toLocaleString()} pcs
• Total Value: ${currencySymbol}${analysis.totalOrderValue.toLocaleString()}
• Expected Profit: ${currencySymbol}${analysis.totalProfit.toLocaleString()}

_Generated by MerchMate_`;

        try {
            await Share.share({ message });
        } catch (error) {
            console.error('Error sharing:', error);
        }
    };

    const handleShareExcel = async () => {
        try {
            const negotiationInsights = {
                commercialAction: analysis.feasibilityScore.recommendation || 'Review pricing strategy',
                negotiationLevers: []
            };
            const data = buildMarginAnalysisData(inputs, analysis, negotiationInsights);
            const uri = await generateExcelMarginAnalysis(data);
            await shareFile(uri);
        } catch (e) {
            Alert.alert('Unable to share Excel', e?.message || 'Unknown error');
        }
    };

    const handleSharePdf = async () => {
        try {
            const negotiationInsights = {
                commercialAction: analysis.feasibilityScore.recommendation || 'Review pricing strategy',
                negotiationLevers: []
            };
            const data = buildMarginAnalysisData(inputs, analysis, negotiationInsights);
            const uri = await generatePdfMarginAnalysis(data);
            await shareFile(uri);
        } catch (e) {
            Alert.alert('Unable to share PDF', e?.message || 'Unknown error');
        }
    };

    // ========== RENDER SECTIONS ==========

    const renderViewTabs = () => (
        <View style={styles.viewTabs}>
            {[
                { key: 'margin', label: 'Margin', icon: '📈' },
                { key: 'cost', label: 'Cost', icon: '💰' },
            ].map(tab => (
                <TouchableOpacity
                    key={tab.key}
                    style={[styles.viewTab, activeView === tab.key && styles.viewTabActive]}
                    onPress={() => setActiveView(tab.key)}
                >
                    <Text style={styles.viewTabIcon}>{tab.icon}</Text>
                    <Text style={[styles.viewTabText, activeView === tab.key && styles.viewTabTextActive]}>
                        {tab.label}
                    </Text>
                </TouchableOpacity>
            ))}
        </View>
    );

    const renderFeasibilityScore = () => (
        <View style={[styles.feasibilityCard, { borderColor: analysis.feasibilityScore.statusColor }]}>
            <View style={styles.feasibilityHeader}>
                <View style={[styles.scoreCircle, { borderColor: analysis.feasibilityScore.statusColor }]}>
                    <Text style={[styles.scoreValue, { color: analysis.feasibilityScore.statusColor }]}>
                        {analysis.feasibilityScore.score}
                    </Text>
                    <Text style={styles.scoreMax}>/100</Text>
                </View>
                <View style={styles.feasibilityInfo}>
                    <View style={[styles.statusBadge, { backgroundColor: analysis.feasibilityScore.statusColor }]}>
                        <Text style={styles.statusBadgeText}>{analysis.feasibilityScore.status}</Text>
                    </View>
                    <Text style={styles.recommendationText}>{analysis.feasibilityScore.recommendation}</Text>
                </View>
            </View>
            <Text style={styles.justificationText}>{analysis.feasibilityScore.justification}</Text>
        </View>
    );

    const renderMarginView = () => (
        <View>
            {/* Hero Margin Card */}
            <View style={styles.heroCard}>
                <Text style={styles.heroLabel}>GROSS MARGIN</Text>
                <View style={styles.heroValueRow}>
                    <Text style={[styles.heroValue, { color: getMarginStatusColor(analysis.marginPercent) }]}>
                        {analysis.marginPercent.toFixed(1)}%
                    </Text>
                    <View style={[styles.heroStatusBadge, { backgroundColor: getMarginStatusColor(analysis.marginPercent) }]}>
                        <Text style={styles.heroStatusText}>{getMarginStatusLabel(analysis.marginPercent)}</Text>
                    </View>
                </View>
                <Text style={styles.heroSubtext}>
                    {currencySymbol}{analysis.grossMargin.toFixed(2)} per piece
                </Text>
            </View>

            {/* Price Analysis */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>💵</Text>
                    <Text style={styles.cardTitle}>Price Analysis</Text>
                </View>
                <View style={styles.priceRow}>
                    <View style={styles.priceItem}>
                        <Text style={styles.priceLabel}>Buyer Target</Text>
                        <Text style={styles.priceValue}>{currencySymbol}{analysis.inputs.buyerTargetFob.toFixed(2)}</Text>
                    </View>
                    <View style={styles.priceItem}>
                        <Text style={styles.priceLabel}>Your Quote</Text>
                        <Text style={styles.priceValue}>{currencySymbol}{analysis.inputs.quotedFob.toFixed(2)}</Text>
                    </View>
                    <View style={styles.priceItem}>
                        <Text style={styles.priceLabel}>Price Gap</Text>
                        <Text style={[
                            styles.priceValue,
                            analysis.priceGap >= 0 ? styles.pricePositive : styles.priceNegative
                        ]}>
                            {analysis.priceGap >= 0 ? '+' : ''}{currencySymbol}{analysis.priceGap.toFixed(2)}
                        </Text>
                    </View>
                </View>
            </View>

            {/* Break-even & Target */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>🎯</Text>
                    <Text style={styles.cardTitle}>FOB Benchmarks</Text>
                </View>
                <View style={styles.benchmarkRow}>
                    <View style={styles.benchmarkItem}>
                        <Text style={styles.benchmarkLabel}>Break-even FOB</Text>
                        <Text style={styles.benchmarkValue}>{currencySymbol}{analysis.breakEvenFob.toFixed(2)}</Text>
                        <Text style={styles.benchmarkHint}>Zero profit point</Text>
                    </View>
                    <View style={styles.benchmarkDivider} />
                    <View style={styles.benchmarkItem}>
                        <Text style={styles.benchmarkLabel}>Target FOB</Text>
                        <Text style={styles.benchmarkValue}>{currencySymbol}{analysis.targetFobWithProfit.toFixed(2)}</Text>
                        <Text style={styles.benchmarkHint}>At {analysis.inputs.targetProfitPercent}% profit</Text>
                    </View>
                </View>
                <View style={[
                    styles.varianceBanner,
                    analysis.isViable ? styles.variancePositive : styles.varianceNegative
                ]}>
                    <Text style={styles.varianceText}>
                        {analysis.isViable
                            ? `✓ Buyer target is ${currencySymbol}${analysis.targetVariance.toFixed(2)} above your required FOB`
                            : `✗ Buyer target is ${currencySymbol}${Math.abs(analysis.targetVariance).toFixed(2)} below your required FOB`
                        }
                    </Text>
                </View>
            </View>

            {/* Order Value Summary */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>📦</Text>
                    <Text style={styles.cardTitle}>Order Summary</Text>
                    <View style={styles.orderBadge}>
                        <Text style={styles.orderBadgeText}>{analysis.orderSizeCategory}</Text>
                    </View>
                </View>
                <View style={styles.orderGrid}>
                    <View style={styles.orderItem}>
                        <Text style={styles.orderLabel}>Quantity</Text>
                        <Text style={styles.orderValue}>{analysis.inputs.orderQuantity.toLocaleString()}</Text>
                        <Text style={styles.orderUnit}>pieces</Text>
                    </View>
                    <View style={styles.orderItem}>
                        <Text style={styles.orderLabel}>Total Value</Text>
                        <Text style={styles.orderValue}>{currencySymbol}{(analysis.totalOrderValue / 1000).toFixed(1)}K</Text>
                        <Text style={styles.orderUnit}>order value</Text>
                    </View>
                    <View style={styles.orderItem}>
                        <Text style={styles.orderLabel}>Expected Profit</Text>
                        <Text style={[styles.orderValue, analysis.totalProfit > 0 ? styles.profitPositive : styles.profitNegative]}>
                            {currencySymbol}{(analysis.totalProfit / 1000).toFixed(1)}K
                        </Text>
                        <Text style={styles.orderUnit}>total profit</Text>
                    </View>
                </View>
            </View>
        </View>
    );

    const renderCostView = () => (
        <View>
            {/* Total Cost Summary */}
            <View style={styles.totalCostCard}>
                <Text style={styles.totalCostLabel}>TOTAL COST PER PIECE</Text>
                <Text style={styles.totalCostValue}>{currencySymbol}{analysis.totalCost.toFixed(2)}</Text>
                <Text style={styles.costDriverBadge}>{analysis.costDriver} Product</Text>
            </View>

            {/* Cost Breakdown */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>📋</Text>
                    <Text style={styles.cardTitle}>Cost Breakdown</Text>
                </View>
                {Object.entries(analysis.costBreakdown).map(([key, comp]) => (
                    <View key={key} style={[styles.costItem, !comp.enabled && styles.costItemDisabled]}>
                        <View style={styles.costItemLeft}>
                            <Text style={styles.costItemEmoji}>{comp.emoji}</Text>
                            <View>
                                <Text style={styles.costItemLabel}>{comp.label}</Text>
                                <Text style={styles.costItemStatus}>
                                    {comp.enabled ? `${comp.status.charAt(0).toUpperCase() + comp.status.slice(1)}` : 'Excluded'}
                                </Text>
                            </View>
                        </View>
                        <View style={styles.costItemRight}>
                            <Text style={styles.costItemValue}>
                                {currencySymbol}{comp.value.toFixed(2)}
                            </Text>
                            <View style={[
                                styles.costPercentBadge,
                                comp.status === 'critical' && styles.costPercentCritical,
                                comp.status === 'high' && styles.costPercentHigh,
                            ]}>
                                <Text style={[
                                    styles.costPercentText,
                                    (comp.status === 'critical' || comp.status === 'high') && styles.costPercentTextAlert
                                ]}>{comp.percent.toFixed(1)}%</Text>
                            </View>
                        </View>
                    </View>
                ))}
            </View>

            {/* Top Contributors */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>🏆</Text>
                    <Text style={styles.cardTitle}>Top Cost Contributors</Text>
                </View>
                {analysis.topCostContributors.map((cost, index) => (
                    <View key={cost.key} style={styles.topCostItem}>
                        <View style={[styles.topCostRank, index === 0 && styles.topCostRankFirst]}>
                            <Text style={styles.topCostRankText}>#{index + 1}</Text>
                        </View>
                        <View style={styles.topCostInfo}>
                            <Text style={styles.topCostLabel}>{cost.label}</Text>
                            <View style={styles.topCostBar}>
                                <View style={[styles.topCostBarFill, { width: `${Math.min(cost.percent, 100)}%` }]} />
                            </View>
                        </View>
                        <Text style={styles.topCostPercent}>{cost.percent.toFixed(1)}%</Text>
                    </View>
                ))}
            </View>

            {/* Flagged Costs */}
            {analysis.flaggedCosts.length > 0 && (
                <View style={styles.card}>
                    <View style={styles.cardHeader}>
                        <Text style={styles.cardIcon}>⚠️</Text>
                        <Text style={styles.cardTitle}>Cost Alerts</Text>
                    </View>
                    {analysis.flaggedCosts.map((flag, index) => (
                        <View key={index} style={styles.alertItem}>
                            <View style={[
                                styles.alertBadge,
                                flag.status === 'critical' ? styles.alertCritical : styles.alertHigh
                            ]}>
                                <Text style={styles.alertBadgeText}>
                                    {flag.status === 'critical' ? 'CRITICAL' : 'HIGH'}
                                </Text>
                            </View>
                            <Text style={styles.alertText}>{flag.warning}</Text>
                        </View>
                    ))}
                </View>
            )}
        </View>
    );

    return (
        <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
            {/* Style Header */}
            <View style={styles.styleHeader}>
                <View>
                    <Text style={styles.styleName}>{inputs.styleName || 'Untitled Style'}</Text>
                    <Text style={styles.buyerName}>{inputs.buyerName || 'Unknown Buyer'}</Text>
                </View>
                <View style={styles.incoTermBadge}>
                    <Text style={styles.incoTermText}>{inputs.incoterm} • {inputs.currency}</Text>
                </View>
            </View>

            {/* Feasibility Score */}
            {renderFeasibilityScore()}

            {/* View Tabs */}
            {renderViewTabs()}

            {/* Content based on active view */}
            {activeView === 'margin' && renderMarginView()}
            {activeView === 'cost' && renderCostView()}

            {/* Export Section */}
            <View style={styles.exportSection}>
                <Text style={styles.exportTitle}>Export & Share</Text>
                <View style={styles.exportButtons}>
                    <TouchableOpacity style={styles.exportButton} onPress={handleShareText}>
                        <Text style={styles.exportIcon}>💬</Text>
                        <Text style={styles.exportText}>Text</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.exportButton} onPress={handleSharePdf}>
                        <Text style={styles.exportIcon}>📄</Text>
                        <Text style={styles.exportText}>PDF</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.exportButton} onPress={handleShareExcel}>
                        <Text style={styles.exportIcon}>📊</Text>
                        <Text style={styles.exportText}>Excel</Text>
                    </TouchableOpacity>
                </View>
            </View>

            <View style={styles.bottomPadding} />
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f0f2f5' },

    // Style Header
    styleHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e9ecef',
    },
    styleName: { fontSize: 18, fontWeight: '700', color: '#1a1a2e' },
    buyerName: { fontSize: 14, color: '#666', marginTop: 2 },
    incoTermBadge: { backgroundColor: '#f0f0f0', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
    incoTermText: { fontSize: 12, fontWeight: '600', color: '#555' },

    // Feasibility Card
    feasibilityCard: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 16,
        borderLeftWidth: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    feasibilityHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    scoreCircle: {
        width: 70,
        height: 70,
        borderRadius: 35,
        borderWidth: 4,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    scoreValue: { fontSize: 24, fontWeight: '800' },
    scoreMax: { fontSize: 11, color: '#888' },
    feasibilityInfo: { flex: 1 },
    statusBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 10 },
    statusBadgeText: { fontSize: 13, fontWeight: '700', color: '#fff' },
    recommendationText: { fontSize: 18, fontWeight: '700', color: '#1a1a2e', marginTop: 6 },
    justificationText: { fontSize: 13, color: '#666', lineHeight: 20 },

    // View Tabs
    viewTabs: {
        flexDirection: 'row',
        marginHorizontal: 16,
        marginTop: 16,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 4,
    },
    viewTab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        borderRadius: 10,
    },
    viewTabActive: { backgroundColor: '#007bff' },
    viewTabIcon: { fontSize: 16, marginRight: 6 },
    viewTabText: { fontSize: 14, fontWeight: '600', color: '#666' },
    viewTabTextActive: { color: '#fff' },

    // Hero Card
    heroCard: {
        backgroundColor: '#1a1a2e',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
    },
    heroLabel: { fontSize: 12, fontWeight: '700', color: '#888', letterSpacing: 1 },
    heroValueRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    heroValue: { fontSize: 48, fontWeight: '800' },
    heroStatusBadge: { marginLeft: 12, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
    heroStatusText: { fontSize: 12, fontWeight: '700', color: '#fff' },
    heroSubtext: { fontSize: 14, color: '#aaa', marginTop: 8 },

    // Cards
    card: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginTop: 12,
        borderRadius: 14,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 1,
    },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
    cardIcon: { fontSize: 18, marginRight: 10 },
    cardTitle: { fontSize: 15, fontWeight: '700', color: '#1a1a2e', flex: 1 },

    // Price Row
    priceRow: { flexDirection: 'row' },
    priceItem: { flex: 1, alignItems: 'center' },
    priceLabel: { fontSize: 11, color: '#888', marginBottom: 4 },
    priceValue: { fontSize: 17, fontWeight: '700', color: '#1a1a2e' },
    pricePositive: { color: '#28a745' },
    priceNegative: { color: '#dc3545' },

    // Benchmark Row
    benchmarkRow: { flexDirection: 'row', marginBottom: 12 },
    benchmarkItem: { flex: 1, alignItems: 'center' },
    benchmarkLabel: { fontSize: 12, color: '#888', marginBottom: 4 },
    benchmarkValue: { fontSize: 20, fontWeight: '700', color: '#1a1a2e' },
    benchmarkHint: { fontSize: 11, color: '#aaa', marginTop: 2 },
    benchmarkDivider: { width: 1, backgroundColor: '#e9ecef', marginHorizontal: 12 },
    varianceBanner: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 10 },
    variancePositive: { backgroundColor: '#d4edda' },
    varianceNegative: { backgroundColor: '#f8d7da' },
    varianceText: { fontSize: 13, fontWeight: '600', textAlign: 'center' },

    // Order Grid
    orderBadge: { backgroundColor: '#007bff15', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
    orderBadgeText: { fontSize: 11, fontWeight: '600', color: '#007bff' },
    orderGrid: { flexDirection: 'row' },
    orderItem: { flex: 1, alignItems: 'center' },
    orderLabel: { fontSize: 11, color: '#888', marginBottom: 4 },
    orderValue: { fontSize: 18, fontWeight: '700', color: '#1a1a2e' },
    orderUnit: { fontSize: 10, color: '#aaa', marginTop: 2 },
    profitPositive: { color: '#28a745' },
    profitNegative: { color: '#dc3545' },

    // Total Cost Card
    totalCostCard: {
        backgroundColor: '#1a1a2e',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
    },
    totalCostLabel: { fontSize: 12, fontWeight: '700', color: '#888', letterSpacing: 1 },
    totalCostValue: { fontSize: 36, fontWeight: '800', color: '#fff', marginTop: 8 },
    costDriverBadge: {
        backgroundColor: '#007bff',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 10,
        marginTop: 10,
    },

    // Cost Items
    costItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
    },
    costItemDisabled: { opacity: 0.4 },
    costItemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    costItemEmoji: { fontSize: 18, marginRight: 12 },
    costItemLabel: { fontSize: 14, fontWeight: '500', color: '#333' },
    costItemStatus: { fontSize: 11, color: '#888', marginTop: 2 },
    costItemRight: { alignItems: 'flex-end' },
    costItemValue: { fontSize: 15, fontWeight: '600', color: '#1a1a2e' },
    costPercentBadge: { backgroundColor: '#f0f0f0', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, marginTop: 4 },
    costPercentCritical: { backgroundColor: '#dc3545' },
    costPercentHigh: { backgroundColor: '#fd7e14' },
    costPercentText: { fontSize: 11, fontWeight: '600', color: '#666' },
    costPercentTextAlert: { color: '#fff' },

    // Top Cost Items
    topCostItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    topCostRank: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#f0f0f0',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    topCostRankFirst: { backgroundColor: '#ffd700' },
    topCostRankText: { fontSize: 11, fontWeight: '700', color: '#666' },
    topCostInfo: { flex: 1, marginRight: 12 },
    topCostLabel: { fontSize: 13, fontWeight: '500', color: '#333', marginBottom: 6 },
    topCostBar: { height: 6, backgroundColor: '#e9ecef', borderRadius: 3 },
    topCostBarFill: { height: 6, backgroundColor: '#007bff', borderRadius: 3 },
    topCostPercent: { fontSize: 14, fontWeight: '700', color: '#1a1a2e', minWidth: 50, textAlign: 'right' },

    // Alert Items
    alertItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
    alertBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginRight: 10 },
    alertCritical: { backgroundColor: '#dc3545' },
    alertHigh: { backgroundColor: '#fd7e14' },
    alertBadgeText: { fontSize: 9, fontWeight: '700', color: '#fff' },
    alertText: { flex: 1, fontSize: 13, color: '#555', lineHeight: 18 },

    // Export Section
    exportSection: { marginTop: 20, marginHorizontal: 16 },
    exportTitle: { fontSize: 13, fontWeight: '600', color: '#888', textAlign: 'center', marginBottom: 12 },
    exportButtons: { flexDirection: 'row', justifyContent: 'center' },
    exportButton: {
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        marginHorizontal: 6,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    exportIcon: { fontSize: 24, marginBottom: 4 },
    exportText: { fontSize: 12, fontWeight: '600', color: '#555' },

    bottomPadding: { height: 40 },
});

export default BuyerAnalyzerResultScreen;
