// import Slider from '@react-native-community/slider';
import { useEffect, useState } from 'react';
import { Alert, ScrollView, Share, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { buildFOBData, generateExcelFOB, generatePdfFOB, shareFile } from '../utils/exporters';

const ResultScreen = ({ route }) => {
    const { breakdown, inputs } = route.params;

    // Initial profit margin from inputs
    const [profitMargin, setProfitMargin] = useState(inputs.profit_margin_percent);
    // Handle old history items that might not have final_fob_per_doz
    const initialFob = breakdown.final_fob_per_doz || (breakdown.final_fob_per_pc * 12);
    const [finalFob, setFinalFob] = useState(initialFob);

    const handleProfitMarginChange = (value) => {
        // Allow empty string, minus sign, decimal point, or valid decimal numbers
        if (value === '' || value === '-' || value === '.' || /^-?\d*\.?\d*$/.test(value)) {
            setProfitMargin(value);
        }
    };

    useEffect(() => {
        // Recalculate locally when profit margin changes
        // Only calculate if profitMargin is a valid number
        const margin = parseFloat(profitMargin);
        if (isNaN(margin)) {
            return; // Don't update if invalid
        }

        // Formula: Total Cost per Dozen * (1 + Profit/100)
        // Handle old history items that might not have total_cost_per_doz
        const totalCost = breakdown.total_cost_per_doz || (breakdown.total_cost_per_pc * 12);
        const newFobPerDoz = totalCost * (1 + (margin / 100.0));
        setFinalFob(newFobPerDoz);
    }, [profitMargin]);

    const handleShare = async () => {
        // Get consumption info based on garment type
        let consumptionInfo = '';
        if (breakdown.garment_type === 'T-Shirt (Knit)') {
            consumptionInfo = `Fabric Consumption: ${breakdown.total_fabric_req_kg_doz} kg/doz (${breakdown.basic_consumption_kg_doz} kg/doz basic)`;
        } else if (breakdown.garment_type === 'Woven Shirt' || breakdown.garment_type === 'Denim Jeans') {
            consumptionInfo = `Fabric Consumption: ${breakdown.total_fabric_req_yards_doz} yards/doz (${breakdown.basic_consumption_yards_piece} yards/pc basic)`;
        }

        const message = `📊 *FOB COSTING QUOTE*

*Style:* ${inputs.style_name || 'N/A'}
*Buyer:* ${inputs.buyer_name || 'N/A'}
*Garment Type:* ${breakdown.garment_type}
${consumptionInfo}

*COST BREAKDOWN (per dozen):*
• Fabric: $${(breakdown.fabric_cost_per_doz || (breakdown.fabric_cost_per_pc * 12))?.toFixed(2) || '0.00'}
• AOP/Print: $${((inputs.aop_print_cost_per_pc || 0) * 12).toFixed(2)}
• Accessories: $${((inputs.accessories_cost_per_pc || 0) * 12).toFixed(2)}
• CM Cost: $${((inputs.cm_cost_per_pc || 0) * 12).toFixed(2)}
• Washing: $${((inputs.washing_cost_per_pc || 0) * 12).toFixed(2)}
• Commercial: $${((inputs.commercial_cost_per_pc || 0) * 12).toFixed(2)}
• Testing: $${((inputs.testing_cost_per_pc || 0) * 12).toFixed(2)}

*Total Cost:* $${(breakdown.total_cost_per_doz || (breakdown.total_cost_per_pc * 12))?.toFixed(2)}/dz ($${breakdown.total_cost_per_pc?.toFixed(2)}/pc)
*Profit Margin:* ${profitMargin}%

*FINAL FOB PRICE: $${finalFob.toFixed(2)}/dz ($${(finalFob / 12).toFixed(2)}/pc)* ✅

_Generated by MerchMate_`;

        try {
            await Share.share({
                message: message,
            });
        } catch (error) {
            console.error('Error sharing:', error);
        }
    };

    const handleShareExcel = async () => {
        try {
            const data = buildFOBData(inputs, breakdown, finalFob, profitMargin);
            const uri = await generateExcelFOB(data);
            await shareFile(uri);
        } catch (e) {
            Alert.alert('Unable to share Excel', e?.message || 'Unknown error');
        }
    };

    const handleSharePdf = async () => {
        try {
            const data = buildFOBData(inputs, breakdown, finalFob, profitMargin);
            const uri = await generatePdfFOB(data);
            await shareFile(uri);
        } catch (e) {
            Alert.alert('Unable to share PDF', e?.message || 'Unknown error');
        }
    };

    const getGarmentIcon = () => {
        switch (breakdown.garment_type) {
            case 'T-Shirt (Knit)': return '👕';
            case 'Woven Shirt': return '👔';
            case 'Denim Jeans': return '👖';
            default: return '📦';
        }
    };

    const formatCurrency = (value) => {
        return `$${Number(value || 0).toFixed(2)}`;
    };

    const totalCostPerDoz = breakdown.total_cost_per_doz || (breakdown.total_cost_per_pc * 12);
    const fabricCostPerDoz = breakdown.fabric_cost_per_doz || (breakdown.fabric_cost_per_pc * 12);

    return (
        <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
            {/* Hero Card - Final FOB */}
            <View style={styles.heroCard}>
                <View style={styles.heroHeader}>
                    <Text style={styles.heroIcon}>{getGarmentIcon()}</Text>
                    <View style={styles.heroInfo}>
                        <Text style={styles.heroStyle}>{inputs.style_name || 'Style'}</Text>
                        <Text style={styles.heroBuyer}>{inputs.buyer_name || 'Buyer'}</Text>
                    </View>
                </View>
                <View style={styles.heroDivider} />
                <Text style={styles.heroLabel}>FINAL FOB PRICE</Text>
                <View style={styles.heroPriceRow}>
                    <Text style={styles.heroCurrency}>$</Text>
                    <Text style={styles.heroPrice}>{finalFob.toFixed(2)}</Text>
                    <Text style={styles.heroUnit}>/doz</Text>
                </View>
                <View style={styles.heroSubPrice}>
                    <Text style={styles.heroSubPriceText}>
                        ${(finalFob / 12).toFixed(2)} per piece
                    </Text>
                </View>
                <View style={styles.garmentBadge}>
                    <Text style={styles.garmentBadgeText}>{breakdown.garment_type}</Text>
                </View>
            </View>

            {/* Profit Margin Adjuster */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>📈</Text>
                    <Text style={styles.cardTitle}>Profit Margin</Text>
                </View>
                <View style={styles.profitRow}>
                    <View style={styles.profitInputContainer}>
                        <TextInput
                            style={styles.profitInput}
                            keyboardType="decimal-pad"
                            value={String(profitMargin)}
                            onChangeText={handleProfitMarginChange}
                            selectTextOnFocus
                        />
                        <Text style={styles.profitPercent}>%</Text>
                    </View>
                    <View style={styles.profitPresets}>
                        {[5, 10, 15, 20].map((preset) => (
                            <TouchableOpacity
                                key={preset}
                                style={[
                                    styles.presetButton,
                                    parseFloat(profitMargin) === preset && styles.presetButtonActive
                                ]}
                                onPress={() => setProfitMargin(preset)}
                            >
                                <Text style={[
                                    styles.presetText,
                                    parseFloat(profitMargin) === preset && styles.presetTextActive
                                ]}>{preset}%</Text>
                            </TouchableOpacity>
                        ))}
                    </View>
                </View>
            </View>

            {/* Cost Breakdown */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>💰</Text>
                    <Text style={styles.cardTitle}>Cost Breakdown</Text>
                    <View style={styles.perDozenBadge}>
                        <Text style={styles.perDozenText}>per dozen</Text>
                    </View>
                </View>
                <View style={styles.costTable}>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>🧵</Text>
                            <Text style={styles.costLabel}>Fabric</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency(fabricCostPerDoz)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>🎨</Text>
                            <Text style={styles.costLabel}>Print/AOP</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.aop_print_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>🔘</Text>
                            <Text style={styles.costLabel}>Accessories</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.accessories_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>✂️</Text>
                            <Text style={styles.costLabel}>CM Cost</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.cm_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>💧</Text>
                            <Text style={styles.costLabel}>Washing</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.washing_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>📋</Text>
                            <Text style={styles.costLabel}>Commercial</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.commercial_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.costRow}>
                        <View style={styles.costLabelRow}>
                            <Text style={styles.costEmoji}>🔬</Text>
                            <Text style={styles.costLabel}>Testing</Text>
                        </View>
                        <Text style={styles.costValue}>{formatCurrency((inputs.testing_cost_per_pc || 0) * 12)}</Text>
                    </View>
                    <View style={styles.totalRow}>
                        <Text style={styles.totalLabel}>Total Cost</Text>
                        <Text style={styles.totalValue}>{formatCurrency(totalCostPerDoz)}</Text>
                    </View>
                </View>
            </View>

            {/* Consumption Details */}
            <View style={styles.card}>
                <View style={styles.cardHeader}>
                    <Text style={styles.cardIcon}>📦</Text>
                    <Text style={styles.cardTitle}>Consumption Details</Text>
                </View>
                <View style={styles.consumptionGrid}>
                    {breakdown.garment_type === 'T-Shirt (Knit)' ? (
                        <>
                            <View style={styles.consumptionItem}>
                                <Text style={styles.consumptionValue}>{breakdown.basic_consumption_kg_doz}</Text>
                                <Text style={styles.consumptionLabel}>Basic (kg/doz)</Text>
                            </View>
                            <View style={styles.consumptionDivider} />
                            <View style={styles.consumptionItem}>
                                <Text style={styles.consumptionValue}>{breakdown.total_fabric_req_kg_doz}</Text>
                                <Text style={styles.consumptionLabel}>With {inputs.wastage_percent}% wastage</Text>
                            </View>
                        </>
                    ) : (
                        <>
                            <View style={styles.consumptionItem}>
                                <Text style={styles.consumptionValue}>{breakdown.basic_consumption_yards_piece}</Text>
                                <Text style={styles.consumptionLabel}>Basic (yards/pc)</Text>
                            </View>
                            <View style={styles.consumptionDivider} />
                            <View style={styles.consumptionItem}>
                                <Text style={styles.consumptionValue}>{breakdown.total_fabric_req_yards_doz}</Text>
                                <Text style={styles.consumptionLabel}>With {inputs.shirt_wastage_percent || inputs.jeans_wastage_percent}% (yards/doz)</Text>
                            </View>
                        </>
                    )}
                </View>
            </View>

            {/* Share Actions */}
            <View style={styles.actionsContainer}>
                <Text style={styles.actionsTitle}>Share & Export</Text>
                <View style={styles.actionsRow}>
                    <TouchableOpacity style={[styles.actionButton, styles.excelButton]} onPress={handleShareExcel}>
                        <Text style={styles.actionIcon}>📊</Text>
                        <Text style={styles.actionLabel}>Excel</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={[styles.actionButton, styles.pdfButton]} onPress={handleSharePdf}>
                        <Text style={styles.actionIcon}>📄</Text>
                        <Text style={styles.actionLabel}>PDF</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={[styles.actionButton, styles.quoteButton]} onPress={handleShare}>
                        <Text style={styles.actionIcon}>💬</Text>
                        <Text style={styles.actionLabel}>Quote</Text>
                    </TouchableOpacity>
                </View>
            </View>

            <View style={{ height: 40 }} />
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f0f2f5',
    },
    heroCard: {
        backgroundColor: '#007bff',
        margin: 16,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#007bff',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 8,
    },
    heroHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        marginBottom: 16,
    },
    heroIcon: {
        fontSize: 40,
        marginRight: 12,
    },
    heroInfo: {
        flex: 1,
    },
    heroStyle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
    heroBuyer: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        marginTop: 2,
    },
    heroDivider: {
        width: '100%',
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.2)',
        marginBottom: 16,
    },
    heroLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: 'rgba(255,255,255,0.8)',
        letterSpacing: 1,
        marginBottom: 8,
    },
    heroPriceRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
    },
    heroCurrency: {
        fontSize: 28,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 8,
    },
    heroPrice: {
        fontSize: 56,
        fontWeight: '800',
        color: '#fff',
        lineHeight: 60,
    },
    heroUnit: {
        fontSize: 18,
        color: 'rgba(255,255,255,0.8)',
        marginBottom: 12,
        marginLeft: 4,
    },
    heroSubPrice: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        marginTop: 8,
    },
    heroSubPriceText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    garmentBadge: {
        position: 'absolute',
        top: 16,
        right: 16,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    garmentBadgeText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '600',
    },
    card: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginBottom: 16,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        overflow: 'hidden',
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: '#f8f9fa',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    cardIcon: {
        fontSize: 20,
        marginRight: 10,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    perDozenBadge: {
        backgroundColor: '#007bff15',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    perDozenText: {
        fontSize: 11,
        color: '#007bff',
        fontWeight: '600',
    },
    profitRow: {
        padding: 16,
    },
    profitInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    profitInput: {
        fontSize: 32,
        fontWeight: '700',
        color: '#007bff',
        textAlign: 'center',
        minWidth: 80,
        borderBottomWidth: 2,
        borderBottomColor: '#007bff',
        paddingVertical: 4,
    },
    profitPercent: {
        fontSize: 24,
        fontWeight: '600',
        color: '#007bff',
        marginLeft: 4,
    },
    profitPresets: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 10,
    },
    presetButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#f0f2f5',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    presetButtonActive: {
        backgroundColor: '#007bff',
        borderColor: '#007bff',
    },
    presetText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    presetTextActive: {
        color: '#fff',
    },
    costTable: {
        padding: 16,
    },
    costRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f2f5',
    },
    costLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    costEmoji: {
        fontSize: 16,
        marginRight: 10,
    },
    costLabel: {
        fontSize: 15,
        color: '#555',
    },
    costValue: {
        fontSize: 15,
        fontWeight: '600',
        color: '#333',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 16,
        marginTop: 8,
        borderTopWidth: 2,
        borderTopColor: '#007bff',
    },
    totalLabel: {
        fontSize: 17,
        fontWeight: '700',
        color: '#333',
    },
    totalValue: {
        fontSize: 20,
        fontWeight: '800',
        color: '#007bff',
    },
    consumptionGrid: {
        flexDirection: 'row',
        padding: 16,
    },
    consumptionItem: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 8,
    },
    consumptionDivider: {
        width: 1,
        backgroundColor: '#e0e0e0',
        marginHorizontal: 16,
    },
    consumptionValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#007bff',
        marginBottom: 4,
    },
    consumptionLabel: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
    },
    actionsContainer: {
        marginHorizontal: 16,
        marginBottom: 16,
    },
    actionsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
        marginBottom: 12,
        textAlign: 'center',
    },
    actionsRow: {
        flexDirection: 'row',
        gap: 12,
    },
    actionButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 16,
        borderRadius: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    excelButton: {
        backgroundColor: '#10b981',
    },
    pdfButton: {
        backgroundColor: '#ef4444',
    },
    quoteButton: {
        backgroundColor: '#007bff',
    },
    actionIcon: {
        fontSize: 28,
        marginBottom: 6,
    },
    actionLabel: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '700',
    },
});

export default ResultScreen;
