// XLSX-based Excel exporters for mobile compatibility
// These use proper .xlsx format instead of HTML-based .xls files

import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as XLSX from 'xlsx';

const toNumber = (v) => {
    const n = typeof v === 'string' ? parseFloat(v) : v;
    return isNaN(n) ? 0 : n;
};

const timestamp = () => {
    const d = new Date();
    const pad = (x) => String(x).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}-${pad(d.getSeconds())}`;
};

const formatNumber = (num, decimals = 2) => {
    if (num === undefined || num === null) return '-';
    return Number(num).toFixed(decimals);
};

/**
 * Generate FOB Costing Excel file in .xlsx format
 */
export const generateExcelFOB_XLSX = async (data) => {
    const generatedDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
    });

    // Create workbook and worksheet
    const workbook = XLSX.utils.book_new();

    // Build data arrays
    const wsData = [
        ['MerchMate - FOB COSTING SHEET'],
        [`Generated: ${generatedDate}`],
        [],
        ['STYLE DETAILS'],
        ['Style Name', data.style],
        ['Buyer', data.buyer],
        ['Garment Type', data.garmentType],
        [],
        ['COST BREAKDOWN'],
        ['Component', 'Per Piece ($)', 'Per Dozen ($)'],
        ['Fabric', data.costs.fabricPerPc.toFixed(2), data.costs.fabricPerDoz.toFixed(2)],
        ['Print/AOP', data.costs.printPerPc.toFixed(2), data.costs.printPerDoz.toFixed(2)],
        ['Accessories', data.costs.accessoriesPerPc.toFixed(2), data.costs.accessoriesPerDoz.toFixed(2)],
        ['CM Cost', data.costs.cmPerPc.toFixed(2), data.costs.cmPerDoz.toFixed(2)],
        ['Washing', data.costs.washingPerPc.toFixed(2), data.costs.washingPerDoz.toFixed(2)],
        ['Commercial', data.costs.commercialPerPc.toFixed(2), data.costs.commercialPerDoz.toFixed(2)],
        ['Testing', data.costs.testingPerPc.toFixed(2), data.costs.testingPerDoz.toFixed(2)],
        [],
        ['SUMMARY'],
        ['Item', 'Per Piece ($)', 'Per Dozen ($)'],
        ['Total Cost', data.totalCostPerPc.toFixed(2), data.totalCostPerDoz.toFixed(2)],
        ['Profit Margin', `${data.profitMargin}%`, ''],
        ['★ FINAL FOB PRICE', data.finalFobPerPc.toFixed(2), data.finalFobPerDoz.toFixed(2)],
        [],
        ['CONSUMPTION'],
        [data.consumption.basicLabel, data.consumption.basic],
        [data.consumption.totalLabel, data.consumption.total],
        [],
        ['Generated by MerchMate - Your Garment Costing Partner']
    ];

    // Create worksheet from array
    const worksheet = XLSX.utils.aoa_to_sheet(wsData);

    // Set column widths
    worksheet['!cols'] = [
        { wch: 30 }, // Column A
        { wch: 15 }, // Column B
        { wch: 15 }  // Column C
    ];

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, 'FOB Costing');

    // Generate binary string
    const wbout = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' });

    // Save to file
    const safeStyle = String(data.style).replace(/[^a-z0-9_-]/gi, '_');
    const fileName = `MerchMate_FOB_${safeStyle}_${timestamp()}.xlsx`;
    const fileUri = FileSystem.documentDirectory + fileName;

    await FileSystem.writeAsStringAsync(fileUri, wbout, { encoding: FileSystem.EncodingType.Base64 });
    return fileUri;
};

/**
 * Generate Fabric Analysis Excel file in .xlsx format
 */
export const generateFabricAnalysisExcel_XLSX = async (data) => {
    const unit = data.unit;
    const priceLabel = unit === 'kg' ? '/kg' : '/yard';
    const price = data.fabricPricePerKg || data.fabricPricePerYard;
    const dimensionUnit = data.garmentType === 'knit' ? 'cm' : 'in';
    const generatedDate = new Date().toLocaleString();

    const getGarmentTypeLabel = (type) => {
        switch (type) {
            case 'knit': return 'Knit (T-Shirt/Polo)';
            case 'woven': return 'Woven (Shirt/Blouse)';
            case 'denim': return 'Denim (Jeans/Jacket)';
            default: return type;
        }
    };

    // Create workbook
    const workbook = XLSX.utils.book_new();

    // Build data arrays
    const wsData = [
        ['MerchMate - FABRIC ANALYSIS'],
        [`Generated: ${generatedDate}`],
        [],
        ['STYLE INFORMATION'],
        ['Style Name', data.styleName || 'N/A'],
        ['Buyer', data.buyerName || 'N/A'],
        ['Garment Type', getGarmentTypeLabel(data.garmentType)],
        [],
        ['KEY RESULTS'],
        ['Metric', 'Value', 'Unit'],
        ['Actual Consumption/Piece', formatNumber(data.actualConsumptionPerPiece, 4), unit],
        ['Consumption/Dozen', formatNumber(data.consumptionPerDozen, 4), unit],
        ['Fabric Cost/Piece', `$${formatNumber(data.fabricCostPerPiece)}`, 'USD'],
        ['Total Fabric Required', formatNumber(data.totalFabricRequired), unit],
        [],
        ['CONSUMPTION SUMMARY'],
        ['Metric', 'Value', 'Unit'],
        ['Theoretical Consumption/pc', formatNumber(data.theoreticalConsumptionPerPiece, 4), unit],
        ['Actual Consumption/pc', formatNumber(data.actualConsumptionPerPiece, 4), unit],
        ['Consumption/Dozen', formatNumber(data.consumptionPerDozen, 4), unit],
        ['Waste/Piece', formatNumber(data.wastePerPiece, 4), unit],
        [],
        ['PATTERN SPECIFICATIONS'],
        ['Parameter', 'Value', 'Unit'],
        ['Original Pattern Length', data.inputs?.patternLength || 'N/A', dimensionUnit],
        ['Original Pattern Width', data.inputs?.patternWidth || 'N/A', dimensionUnit],
        ['Adjusted Pattern Length', formatNumber(data.adjustedPatternLength), dimensionUnit],
        ['Adjusted Pattern Width', formatNumber(data.adjustedPatternWidth), dimensionUnit],
        ['Fabric Width', data.inputs?.fabricWidth || 'N/A', dimensionUnit],
    ];

    // Add garment-specific rows
    if (data.garmentType === 'knit') {
        wsData.push(['GSM (Grams/Sq Meter)', data.inputs?.gsm || 'N/A', '']);
    }
    if (data.garmentType === 'denim') {
        wsData.push(['Fabric Weight', data.inputs?.fabricWeight || 'N/A', 'oz/sq.yd']);
    }

    // Continue with efficiency metrics
    wsData.push(
        [],
        ['EFFICIENCY METRICS'],
        ['Metric', 'Value', 'Benchmark'],
        ['Marker Efficiency', `${data.markerEfficiency}%`, '75-85% typical'],
        ['Fabric Utilization', `${formatNumber(data.fabricUtilization)}%`, ''],
        ['Total Waste Percentage', `${formatNumber(data.wastePercentage)}%`, '<10% ideal'],
        [],
        ['ALLOWANCES APPLIED'],
        ['Type', 'Length', 'Width'],
        ['Shrinkage', `${data.inputs?.shrinkageLength || 0}%`, `${data.inputs?.shrinkageWidth || 0}%`],
        ['Wastage Allowance', `${data.inputs?.wastage || 0}%`, ''],
        [],
        ['ORDER REQUIREMENTS'],
        ['Parameter', 'Value', 'Unit'],
        ['Order Quantity', data.orderQuantity?.toLocaleString() || 'N/A', 'pieces'],
        ['Total Fabric Required', formatNumber(data.totalFabricRequired), unit],
        ['Total Fabric (Meters)', formatNumber(data.totalFabricMeters), 'm'],
        ['Total Waste', formatNumber(data.totalWaste), unit],
        [],
        ['COST ANALYSIS'],
        ['Item', 'Value', 'Unit'],
        ['Fabric Price', `$${formatNumber(price)}`, priceLabel],
        ['Cost/Piece', `$${formatNumber(data.fabricCostPerPiece)}`, 'USD'],
        ['Cost/Dozen', `$${formatNumber(data.fabricCostPerDozen)}`, 'USD'],
        ['Total Fabric Cost', `$${formatNumber(data.totalFabricCost)}`, 'USD']
    );

    // Add FOB impact if available
    if (data.fobData) {
        wsData.push(
            [],
            ['FOB IMPACT ANALYSIS'],
            ['Component', 'Amount', 'Percentage'],
            ['Fabric Cost/Piece', `$${formatNumber(data.fobData.fabricCostPerPiece)}`, `${formatNumber(data.fobData.fabricPercentageOfFOB)}% of FOB`],
            ['Other Costs/Piece', `$${formatNumber(data.fobData.otherCostsPerPiece)}`, ''],
            ['Total Cost/Piece', `$${formatNumber(data.fobData.totalCostPerPiece)}`, ''],
            [],
            ['FINAL FOB'],
            ['FOB Per Piece', `$${formatNumber(data.fobData.fobPerPiece)}`, `@ ${data.profitMargin}% margin`],
            ['FOB Per Dozen', `$${formatNumber(data.fobData.fobPerDozen)}`, '']
        );
    }

    wsData.push(
        [],
        ['Generated by MerchMate - Fabric Consumption Analyzer']
    );

    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(wsData);

    // Set column widths
    worksheet['!cols'] = [
        { wch: 35 }, // Column A
        { wch: 20 }, // Column B
        { wch: 20 }  // Column C
    ];

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Fabric Analysis');

    // Generate binary string
    const wbout = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' });

    // Save to file
    const safeStyle = String(data.styleName || 'analysis').replace(/[^a-z0-9_-]/gi, '_');
    const fileName = `MerchMate_Fabric_${safeStyle}_${timestamp()}.xlsx`;
    const fileUri = FileSystem.documentDirectory + fileName;

    await FileSystem.writeAsStringAsync(fileUri, wbout, { encoding: FileSystem.EncodingType.Base64 });
    return fileUri;
};

/**
 * Generate Margin Analysis Excel file in .xlsx format
 */
export const generateMarginAnalysisExcel_XLSX = async (data) => {
    const generatedDate = new Date().toLocaleString();

    // Create workbook
    const workbook = XLSX.utils.book_new();

    // Build data arrays
    const wsData = [
        ['MerchMate - MARGIN ANALYSIS'],
        [`Generated: ${generatedDate}`],
        [],
        ['STYLE INFORMATION'],
        ['Style Name', data.styleName || 'N/A'],
        ['Buyer', data.buyerName || 'N/A'],
        ['Feasibility Score', `${data.feasibilityScore.score}/100 - ${data.feasibilityScore.status}`],
        ['Recommendation', data.feasibilityScore.recommendation],
        [],
        ['PRICING ANALYSIS'],
        ['Item', 'Amount ($)'],
        ['Buyer Target FOB', data.buyerTargetFob.toFixed(2)],
        ['Your Quoted FOB', data.quotedFob.toFixed(2)],
        ['Price Gap', data.priceGap.toFixed(2)],
        ['Break-even FOB', data.breakEvenFob.toFixed(2)],
        [`Target FOB (at ${data.targetProfitPercent}% profit)`, data.targetFobWithProfit.toFixed(2)],
        ['Variance from Buyer Target', data.targetVariance.toFixed(2)],
        [],
        ['MARGIN ANALYSIS'],
        ['Metric', 'Value'],
        ['Gross Margin', `$${data.grossMargin.toFixed(2)} per piece`],
        ['Margin Percentage', `${data.marginPercent.toFixed(1)}%`],
        ['Profit Per Piece', `$${data.grossMargin.toFixed(2)}`],
        [],
        ['COST BREAKDOWN'],
        ['Component', 'Amount ($)', 'Percentage (%)']
    ];

    // Add cost breakdown entries
    Object.entries(data.costBreakdown).forEach(([key, comp]) => {
        wsData.push([
            comp.label,
            comp.value.toFixed(2),
            comp.percent.toFixed(1)
        ]);
    });

    wsData.push(
        ['TOTAL COST', data.totalCost.toFixed(2), '100.0'],
        [],
        ['PRODUCTION DETAILS'],
        ['Cost Driver Category', data.costDriver],
        []
    );

    // Add cost alerts if any
    if (data.flaggedCosts && data.flaggedCosts.length > 0) {
        wsData.push(
            ['COST ALERTS'],
            ['Warning']
        );
        data.flaggedCosts.forEach(flag => {
            wsData.push([flag.warning]);
        });
        wsData.push([]);
    }

    // Order summary
    wsData.push(
        ['ORDER SUMMARY'],
        ['Parameter', 'Value'],
        ['Order Quantity', `${data.orderQuantity.toLocaleString()} pieces`],
        ['Order Category', data.orderSizeCategory],
        ['Total Order Value', `$${data.totalOrderValue.toFixed(2)}`],
        ['Expected Total Profit', `$${data.totalProfit.toFixed(2)}`],
        []
    );

    // Negotiation insights
    if (data.negotiationInsights.negotiationLevers && data.negotiationInsights.negotiationLevers.length > 0) {
        wsData.push(
            ['NEGOTIATION LEVERS'],
            ['Lever', 'Description', 'Target Improvement']
        );
        data.negotiationInsights.negotiationLevers.forEach(lever => {
            wsData.push([
                lever.lever,
                lever.description,
                lever.targetImprovement
            ]);
        });
        wsData.push([]);
    }

    wsData.push(
        ['COMMERCIAL RECOMMENDATION'],
        [data.negotiationInsights.commercialAction],
        [],
        ['Generated by MerchMate - Buyer-Centric Margin Analyzer']
    );

    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(wsData);

    // Set column widths
    worksheet['!cols'] = [
        { wch: 35 }, // Column A
        { wch: 20 }, // Column B
        { wch: 20 }  // Column C
    ];

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Margin Analysis');

    // Generate binary string
    const wbout = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' });

    // Save to file
    const safeStyle = String(data.styleName || 'analysis').replace(/[^a-z0-9_-]/gi, '_');
    const fileName = `MerchMate_Margin_${safeStyle}_${timestamp()}.xlsx`;
    const fileUri = FileSystem.documentDirectory + fileName;

    await FileSystem.writeAsStringAsync(fileUri, wbout, { encoding: FileSystem.EncodingType.Base64 });
    return fileUri;
};

/**
 * Share file using Sharing API
 */
export const shareFile = async (uri) => {
    const available = await Sharing.isAvailableAsync();
    if (!available) {
        throw new Error('Sharing is not available on this device');
    }
    await Sharing.shareAsync(uri);
};
